/**
 * Atherum Core — Report Types (Scribe Engine)
 *
 * Scribe is a ReACT agent that generates multi-section reports by querying
 * knowledge graphs, deliberation outcomes, and external data. Reports are
 * generated incrementally (section by section) and support follow-up chat.
 */

import type {
  ReportId,
  SessionId,
  KnowledgeGraphId,
  WorkspaceId,
} from "../ids";

// ---------------------------------------------------------------------------
// Report request
// ---------------------------------------------------------------------------

export interface ReportRequest {
  workspaceId: WorkspaceId;
  /** What kind of report */
  template: ReportTemplate;
  /** Data sources the agent can query */
  sources: ReportSource[];
  /** Natural language description of what the report should cover */
  brief: string;
  /** Cost budget for the entire report generation */
  costBudgetUsd: number;
}

export type ReportTemplate =
  | "content-review-summary"
  | "campaign-analysis"
  | "trend-report"
  | "crisis-assessment"
  | "brand-health"
  | "consensus-map"
  | "custom";

export type ReportSource =
  | { type: "deliberation"; sessionId: SessionId }
  | { type: "simulation"; simulationId: string }
  | { type: "knowledge-graph"; graphId: KnowledgeGraphId }
  | { type: "external-data"; url: string; description: string };

// ---------------------------------------------------------------------------
// Report plan — generated by the planner before execution
// ---------------------------------------------------------------------------

export interface ReportPlan {
  reportId: ReportId;
  title: string;
  sections: PlannedSection[];
  estimatedCostUsd: number;
}

export interface PlannedSection {
  sectionIndex: number;
  title: string;
  /** What the agent plans to do for this section */
  approach: string;
  /** Which tools/sources the agent plans to use */
  plannedTools: string[];
  /** Dependencies on other sections (must complete first) */
  dependsOn: number[];
}

// ---------------------------------------------------------------------------
// Report — the generated artifact
// ---------------------------------------------------------------------------

export interface Report {
  id: ReportId;
  workspaceId: WorkspaceId;
  request: ReportRequest;
  plan: ReportPlan;
  status: "planning" | "generating" | "completed" | "failed";

  /** Generated sections */
  sections: ReportSection[];

  /** ReACT agent trace — full reasoning + tool calls */
  agentTrace: AgentTraceStep[];

  /** Follow-up conversation history */
  followUpMessages: FollowUpMessage[];

  costUsd: number;
  createdAt: Date;
  completedAt?: Date;
}

export interface ReportSection {
  sectionIndex: number;
  title: string;
  /** Rendered markdown content */
  content: string;
  /** Data visualizations / charts embedded in this section */
  visualizations?: Array<{
    type: "bar" | "line" | "pie" | "heatmap" | "network";
    data: Record<string, unknown>;
    caption: string;
  }>;
  /** Sources cited in this section */
  citations: Array<{
    sourceType: string;
    reference: string;
    relevance: string;
  }>;
  status: "pending" | "generating" | "completed" | "failed";
}

// ---------------------------------------------------------------------------
// Agent trace — ReACT loop transparency
// ---------------------------------------------------------------------------

export interface AgentTraceStep {
  stepIndex: number;
  type: "thought" | "action" | "observation";
  content: string;
  /** If action, which tool was called */
  toolCall?: {
    tool: string;
    input: Record<string, unknown>;
    output: string;
    durationMs: number;
  };
  tokenUsage: { input: number; output: number };
  timestamp: Date;
}

// ---------------------------------------------------------------------------
// Follow-up chat
// ---------------------------------------------------------------------------

export interface FollowUpMessage {
  role: "user" | "assistant";
  content: string;
  /** If assistant used tools to answer */
  toolCalls?: AgentTraceStep[];
  timestamp: Date;
}
