/**
 * Atherum Core — Simulation Types
 *
 * Simulation creates social environments where content propagates through
 * agent networks. Powered by OASIS (Python) but orchestrated from TypeScript.
 */

import type {
  SimulationId,
  PersonaId,
  WorkspaceId,
  SessionId,
} from "../ids";

// ---------------------------------------------------------------------------
// Platform types — which social environment to simulate
// ---------------------------------------------------------------------------

export type SimulationPlatform = "twitter" | "reddit";

export interface PlatformConfig {
  platform: SimulationPlatform;
  /** Number of simulated agents in the environment */
  agentCount: number;
  /** Simulation duration in virtual hours */
  durationHours: number;
  /** Time compression factor — 1 virtual hour = N real seconds */
  timeCompression: number;
  /** Which recommendation algorithm to use */
  recsAlgorithm: "chronological" | "engagement-weighted" | "controversy-boosted";
}

// ---------------------------------------------------------------------------
// Content injection — what gets seeded into the simulation
// ---------------------------------------------------------------------------

export interface SimulationSeed {
  /** Content to inject into the simulated platform */
  content: Array<{
    type: "post" | "ad" | "thread";
    text: string;
    mediaUrls?: string[];
    /** Which simulated account posts this */
    authorPersonaId?: PersonaId;
    /** When to inject (virtual timestamp) */
    injectAtHour: number;
  }>;
  /** Optional: competing content to test against */
  variants?: Array<{
    variantId: string;
    label: string; // e.g. "Version A", "Version B"
    content: SimulationSeed["content"];
  }>;
}

// ---------------------------------------------------------------------------
// Simulation request — sent to OASIS worker
// ---------------------------------------------------------------------------

export interface SimulationRequest {
  id: SimulationId;
  workspaceId: WorkspaceId;
  platform: PlatformConfig;
  seed: SimulationSeed;
  /** Personas to include as agents (mapped to OASIS agent profiles) */
  personas: PersonaId[];
  /** Additional background agents generated by OASIS */
  backgroundAgentCount: number;
  /** Cost budget */
  costBudgetUsd: number;
  /** Callback URL for progress updates */
  callbackUrl?: string;
}

// ---------------------------------------------------------------------------
// Simulation progress — streamed back from OASIS
// ---------------------------------------------------------------------------

export interface SimulationProgress {
  simulationId: SimulationId;
  virtualHour: number;
  totalHours: number;
  metrics: {
    totalPosts: number;
    totalEngagements: number;
    activeAgents: number;
  };
  /** Significant events detected */
  events: SimulationEvent[];
}

export type SimulationEvent =
  | { type: "viral-threshold"; postId: string; engagements: number; hour: number }
  | { type: "echo-chamber-formed"; clusterSize: number; topic: string; hour: number }
  | { type: "sentiment-shift"; direction: "positive" | "negative"; magnitude: number; hour: number }
  | { type: "controversy-spike"; topic: string; polarization: number; hour: number };

// ---------------------------------------------------------------------------
// Simulation result — final output
// ---------------------------------------------------------------------------

export interface SimulationResult {
  simulationId: SimulationId;
  status: "completed" | "budget-exceeded" | "failed";

  /** Per-content propagation metrics */
  propagation: Array<{
    contentIndex: number;
    variantId?: string;
    impressions: number;
    engagements: number;
    shares: number;
    sentimentDistribution: {
      positive: number;
      neutral: number;
      negative: number;
    };
    reachByHour: Array<{ hour: number; cumulativeReach: number }>;
    topComments: Array<{
      agentPersonaId: PersonaId;
      text: string;
      sentiment: number;
      engagements: number;
    }>;
  }>;

  /** Network-level analysis */
  network: {
    /** Identified communities/clusters */
    clusters: Array<{
      id: string;
      size: number;
      dominantSentiment: string;
      keyInfluencers: PersonaId[];
      echo: number; // 0..1, how echo-chamber-like
    }>;
    /** Information flow paths */
    propagationPaths: Array<{
      from: PersonaId;
      to: PersonaId;
      contentIndex: number;
      hopCount: number;
    }>;
  };

  /** Timeline of significant events */
  timeline: SimulationEvent[];

  /** Cost */
  costUsd: number;
  completedAt: Date;
}
